In [1]:
import torch

In [2]:
print(torch.__version__)

1.4.0


In [3]:
tensor_array = torch.Tensor([[1, 2], [4,5]])

In [4]:
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [9]:
tensor_uninitialised = torch.Tensor(3,3)

In [10]:
tensor_uninitialised

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.numel(tensor_uninitialised)

9

In [12]:
tensor_uninitialised

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
tensor_initialised = torch.randn(2, 3)
tensor_initialised

tensor([[-0.3870,  2.4065, -2.8146],
        [-1.1872,  1.1423, -0.0396]])

In [15]:
tensor_int = torch.randn(5, 3).type(torch.IntTensor)

In [16]:
tensor_int

tensor([[-1,  0,  0],
        [-2,  1,  0],
        [-1,  0, -1],
        [ 0,  0,  0],
        [-1,  0,  0]], dtype=torch.int32)

In [19]:
tensor_byte = torch.ByteTensor([0, 261, 1, -5])

In [20]:
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [21]:
tensor_long = torch.LongTensor([1.0, 2.0, 3.0])

In [22]:
tensor_long

tensor([1, 2, 3])

In [24]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
tensor_zeros = torch.zeros(10)
tensor_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
tensor_eye = torch.eye(3)

tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [31]:
non_zeros = torch.nonzero(tensor_eye)

non_zeros

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [33]:
tensor_ones_shape_eye = torch.ones_like(tensor_eye)

tensor_ones_shape_eye

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [34]:
initial_tensor = torch.randn(3, 3)

initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [36]:
# Tensor math operations

new_tensor = initial_tensor.add(4)
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [38]:
initial_tensor.add_(5)

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

In [39]:
initial_tensor

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

In [40]:
import numpy as np

In [41]:
numpy_arr = np.array([1,2,3])
numpy_arr

array([1, 2, 3])

In [42]:
tensor = torch.from_numpy(numpy_arr)
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [44]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [45]:
numpy_arr[1] = 4
numpy_arr

array([1, 4, 3])

In [46]:
tensor

tensor([1, 4, 3], dtype=torch.int32)

In [53]:
initial_tensor = torch.randn(2,3)

initial_tensor

tensor([[-0.0361,  0.1873, -0.7510],
        [ 0.0601,  0.1710, -0.2352]])

In [52]:
torch.seed()

531463941775057

In [54]:
initial_tensor.shape

torch.Size([2, 3])

In [56]:
initial_tensor.size()

torch.Size([2, 3])

In [59]:
initial_tensor.view(6)

tensor([-0.0361,  0.1873, -0.7510,  0.0601,  0.1710, -0.2352])

In [60]:
initial_tensor

tensor([[-0.0361,  0.1873, -0.7510],
        [ 0.0601,  0.1710, -0.2352]])

In [61]:
resized_tensor = initial_tensor.view(-1, 2)

In [62]:
resized_tensor

tensor([[-0.0361,  0.1873],
        [-0.7510,  0.0601],
        [ 0.1710, -0.2352]])

In [66]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor)
sorted_tensor

tensor([[-0.7510, -0.0361,  0.1873],
        [-0.2352,  0.0601,  0.1710]])

In [67]:
sorted_indices

tensor([[2, 0, 1],
        [2, 0, 1]])

In [68]:
from torch.autograd import Variable

In [69]:
x = Variable(torch.randn(1, 10))
h = Variable(torch.randn(1, 20))
w_h = Variable(torch.randn(20,20))
w_x = Variable(torch.randn(20,10))

In [70]:
h_prod = torch.mm(w_h, h.t())

In [71]:
h_prod

tensor([[ -1.8240],
        [ -8.8889],
        [ -0.9174],
        [ -1.1291],
        [  4.9571],
        [-11.1993],
        [  2.8290],
        [  3.7341],
        [ -0.3211],
        [ -6.8296],
        [  2.6071],
        [ -2.4699],
        [  6.5803],
        [  4.0887],
        [ -3.4027],
        [ -2.5475],
        [  0.3435],
        [ -2.4127],
        [  0.3649],
        [ -3.8465]])

In [74]:
x_prod = torch.mm(w_x, x.t())
x_prod

tensor([[ 0.9434],
        [10.2731],
        [ 0.3296],
        [-1.7080],
        [ 0.7526],
        [ 0.3354],
        [-0.5398],
        [ 1.2413],
        [-7.8473],
        [-4.2000],
        [-2.1892],
        [-0.3657],
        [-5.3426],
        [-0.5587],
        [ 1.4702],
        [-0.7175],
        [-0.8820],
        [ 1.5312],
        [-5.7828],
        [-5.3868]])

In [75]:
next_h = (h_prod + x_prod).tanh()

In [76]:
loss = next_h.sum()